export const REGULAR_PIZZA_LIST_REQUEST = "REGULAR_PIZZA_LIST_REQUEST";
export const REGULAR_PIZZA_LIST_SUCCESS = "REGULAR_PIZZA_LIST_SUCCESS";
export const REGULAR_PIZZA_LIST_FAIL = "REGULAR_PIZZA_LIST_FAIL";

export const PIZZA_BASE_LIST_REQUEST = "PIZZA_BASE_LIST_REQUEST";
export const PIZZA_BASE_LIST_SUCCESS = "PIZZA_BASE_LIST_SUCCESS";
export const PIZZA_BASE_LIST_FAIL = "PIZZA_BASE_LIST_FAIL";

export const SAUCE_LIST_REQUEST = "SAUCE_LIST_REQUEST";
export const SAUCE_LIST_SUCCESS = "SAUCE_LIST_SUCCESS";
export const SAUCE_LIST_FAIL = "SAUCE_LIST_FAIL";

export const CHEESE_LIST_REQUEST = "CHEESE_LIST_REQUEST";
export const CHEESE_LIST_SUCCESS = "CHEESE_LIST_SUCCESS";
export const CHEESE_LIST_FAIL = "CHEESE_LIST_FAIL";

export const MEAT_LIST_REQUEST = "MEAT_LIST_REQUEST";
export const MEAT_LIST_SUCCESS = "MEAT_LIST_SUCCESS";
export const MEAT_LIST_FAIL = "MEAT_LIST_FAIL";

export const VEGGIES_LIST_REQUEST = "VEGGIES_LIST_REQUEST";
export const VEGGIES_LIST_SUCCESS = "VEGGIES_LIST_SUCCESS";
export const VEGGIES_LIST_FAIL = "VEGGIES_LIST_FAIL";